apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-gatekeeper-staging

resources:
- ../../base
images:
- name: jklanica/ai-gatekeeper-migrator
  newName: jklanica/ai-gatekeeper-migrator
  newTag: 6818f164
- name: jklanica/ai-gatekeeper-proxy
  newName: jklanica/ai-gatekeeper-proxy
  newTag: 6818f164
- name: jklanica/ai-gatekeeper-web
  newName: jklanica/ai-gatekeeper-web
  newTag: 6818f164
