apiVersion: v1
kind: Secret
metadata:
  name: ai-gatekeeper-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: ai-gatekeeper
  DATABASE_URL: postgres://ai-gatekeeper:ai-gatekeeper@postgres-service:5432/ai-gatekeeper
  JWT_SECRET: your_super_secret_string_here
