apiVersion: v1
kind: Secret
metadata:
    name: ai-gatekeeper-secret
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0A9zRhdrrYcPw3kNEw==,iv:kAhtyv+xDzTHGPS5YmUzTut/4y3e/n9tKQKS9O9NW4A=,tag:vJNLsBZotNHX/F9JEq1lkA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ee1z1iyKp3Nkib6HDCuwxHjCuEx5irAOkH2wxH4mDQwIvc5VVXbbgLxnV0xK+6Bk/wTYZYuiFFGOq7Fx8GDG4979+aRXUPizWAE=,iv:DqMvvFwA+9kIALfQEjhhpfygsCabAaCIw+ppVRrmklI=,tag:DG8yzP1yZ0Nlktl9Lrkq3A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:kU4xCsW3yfHNQsDV8dlNKv/pTmWwG4bCp8SSxII=,iv:t/ic+7qUOvzHqZTTeEzypV+w80jAbNcZ2eENeYAkB1I=,tag:tt/e5MGnaH6XcawVDdrI4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU0pCaGk5bU91TU5qZW5G
            ZllCWExhdUtycE5VNUw1VEZxSnY0YWNTM2cwClAyTEsxall4SUxFZUorclJ6dm8x
            ZXorWWRYRTN3WTVVc0pJc09EZm5FWmsKLS0tIGdYa2p1Z2RYVk9WNnloY01LQjRm
            bHB2enkzS1dvdHB5MXZjNi9ZMzh4OUEKkVzazdZBhU8hUAFR4+z4UEQVCdzClnwj
            ehVQSHOgXw8Sx30v+P75sWNdphwAjVCrUeRkaqaZC8Mbyiv0zxQmxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134z99v0d7e2wpkgr3z50g0mzppe4dgt8ku8lyceeexm8za446vtskj4rmh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T18:00:37Z"
    mac: ENC[AES256_GCM,data:Zh0t/qqbLoWJ6ToXaW6ilUxJfGlOM5QLL0nxRmKQN1pGncyExHSKnz3tL0cCWo8zxqyjTYp3JFfYWz0QZU1DJNsS3ZjcsChVACm7T/PjzyQIDMuKyMiaCFfhf8EuwrXzPQmR++HAHxwGqemtu/HYUa2yK2Z9YoplPK0o7uUCE+A=,iv:UGZVPBhgju4XRTX43totoHKNotNVKyQLtJKhfS4OssQ=,tag:i86B5tOObsPzXJxXdN85Ow==,type:str]
    version: 3.13.2
