apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-gatekeeper-production

resources:
  - ../../base
  - web-pdb.yaml
  - proxy-pdb.yaml

replicas:
  - name: web
    count: 2
  - name: proxy
    count: 2
