apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-gatekeeper-config
data:
  POSTGRES_USER: ai-gatekeeper
  POSTGRES_DB: ai-gatekeeper
  NODE_ENV: production
  PROXY_PORT: "3001"
  REDIS_URL: redis://redis-service:6379