{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ai-gatekeeper-secret",
    "namespace": "ai-gatekeeper-production",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ai-gatekeeper-secret",
        "namespace": "ai-gatekeeper-production",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "DATABASE_URL": "AgBU0eohRjHBbMiNNCEg+F2mo18mr88ZcGpiOotThPqpkEuMjcZPWzjDEGqGgwcCTBPt6sYkZfZXR5R/+WREsovcjXSqvt5eA9yfgsY0CnWg+iL43T9yjRowMfbzDPlY89rQYjk7pZO5Z5QLvuYVtgUCPugJbFe1sD31aJg1iSiI6ZdRDfFVMX/fWMoTO4ESzKXkBySDmgQQdMhbYp66cU3fcWD3qzXHcDK50rHrOYVG4GCqETdU3NX+hMvYRMiVfPHoW7Cyulp1cghKExodiQkGQhqhqtDmtX4sWAe8oTK897ucct9VIRLJrv+Nqxa+0q/KpdeQ9Ei6Mm2nhPN5PMB4MUgveo9nLmiPfTKSo3vhJTTpMScDIDQCH5l9DAuihiGDSeMLekGZoz5h6771y/UKWlB5zVEZiTtLnFTh2Eubb1XvXc9AG5vQsRZOoaPGdgi4zetPvAcqLXfUY+12h3lp8G11j4CDP6YVBA+Otu0eHLGqRodTn6c6zXzHub2Xa2tvmZVJ1DHPHv/I5nx1XlAyE7zxz+pq+q1jUSJ64iO90T34BxLnY6Ej9dQK7/HrAGht22gU5lIzDTi8uBidIVObXS1weLug6XQrLaNyasWADTU2pNQj3giHNwCOrx4zh8Y71HjMkfzVTUvs887WD5Ir+cX4w6k5tWZ/naddndZIoSa3Gok8Xlef8OjMceIwf2RfKb1IKwUihGzK0UjR/ofciQjOhYwSc5GsUYaaxesnUtQyWbWiofdRs2GG624Rr7XJg/SEVaczjCnqZmGJX+kykOSRoDPx",
      "JWT_SECRET": "AgCEJthkSZZSTPU9tCjWsVcJkuDAGLWvpLCGjJT92ptZ0A6k04CV9ZEENtlwX3lutusVB30/qaZ/OdEwh8KEk8RmmvdN5UHU80gyiu0ce2kGtwnJ1QgP2W3ItDrs1vMFp14bOoykiidjaycpYU1JecDXtclAJ6Dc6ZCAWlm9SHvL+2Y1dLFGtkXRlGsxqRn1uc8fB+Pi6T8fYxmuThGco2NW3LziVDDpuAhuCWsGRjMs7tTN5eaiEi2nCVhXgGwNcuqUYSTc8MoyWa+AFMCj1yK/LgTLZvsaYSlFCGnbrDpw1dh2MOD4iPuuLOsU4SL7r1OBzml8VfupQoGKCyHm4Ks/mVVpdUXeALuyCxYPMevPLorAqPf+7bDL01X6D14aqefaPDYKG1MAZrfVbTwEjQLiyws/cfpA4jbbe/wnGEH5GOmJEQhfxv182k4MKGb/XDwi7H0WJc6Y/4J7+/V0j8pfQCxSPNbT2tlK0Gixo0mXRfkh9tjRaQDTLhkCF3S58sKkqKa+COd6ZPai6HqqZU3JepEjlD4p2no4INSitNB+xggnqu48JL/iBr6hKbWphLPmnvaBXmRc+vnL35GYwTHOIvrTqBJpgLTgcXA8tnZ33/HG6wK1ngfhexToD3JvcH01YAoAGisekMabCj5qGTs/sGSocQuPIAQB7VNBBGyokOGH5sF3UCjfS/6KaFxuVg5cqO4gv7bCFjY=",
      "POSTGRES_PASSWORD": "AgCJx+hVI8JCjSX/weZlbSH86Ju4h0CnvsaA7FZ52AsZqjLTwkudYyLklC4N5k52vcofkmWEsiArHk0o92wYej5Iddkuhd4NuecCOSnQ1NzBGvQn7/BuuFUpJh+pz6WIPj/+fIiXfgiXthps933yLl0VdHp1T+nYLhz6KDBbZMmYYtvi5wExoi+kN7K2OIqtHsx5sDst1EvHapG5w8F7i0xoR4LpK/cgqh/MrlEy8TnZEvAln4FOu6O+dTtw16JOZ20IJRVXf4ST0CiYyq1nrklTICBMy+96I1jlJ2HZ+xNYYPDF7kQTeMMpZ8YMiF6CcIXlVlsXGLzvaOEOfvc01w60Lfu2u1lAMqEKgsQeIMEcIkT2nuKd9AoJbuMA3PkclmdrP1xYD/D6swIh/XhF/bwFdRB0g41f83aXyaOAIt8Siil75MiVfQkm9dAekFMONFTwBXtvxzzmfU0hKzE/Fkg1u8iAtQ6nv8arQqk7mkBM3aGYF3ZfloJKzSOZMPvJW5gXmeks7G9LIYpwlGEhmDWQ3KEgdLVCc+CpIzBe/BZaxCy6RSYbeh0PqrfSgepOmLubQxChZS6rsuJapku7nn6iNGI0KUppHq/3VHPvvDa0Ocllc9KqzrA4n6FqbfeyqSZ6s99M63JZavVoaIDNcWdz6QHEOTLWpRQ8GPceZikWq1X/+qHetkxjEHKgAsKNLoX1OrJXfCa7D+M="
    }
  }
}
